### ISSUE TITLE
Handling of the `DELETE_SUBMISSION` action.

### ISSUE THREAD

**Issue by dh418v** [R190635/NextJsForm#1]
Hello.
I think findIndex() method better than DELETE_SUBMISSION.
What is your opinion?

**Comment by R190635** [comment]
Which file are you talking about?

**Comment by dh418v** [comment]
![image](https://github.com/R190635/NextJsForm/assets/9044633/3d180981-93f5-476b-88b0-e30aae2a2cb4)

**Comment by R190635** [comment]
Ah, okay mate.
I will check it.
thanks
